pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    // Install Node.js dependencies
                    sh 'npm install'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                script {
                    // Build Docker image
                    sh 'docker build -t filthyspartan/miniproject .'
                }
            }
        }
        
        stage('Push to DockerHub') {
            steps {
                script {
                    // Push Docker image to DockerHub
                    withCredentials([usernamePassword(credentialsId: 'your-dockerhub-credentials-id', usernameVariable: 'filthyspartan', passwordVariable: 'GitBastard1!')]) {
                        sh "docker login -u $filthyspartan -p $GitBastard1!"
                        sh 'docker push your-dockerhub-username/your-image-name'
                    }
                }
            }
        }
    }
}
